version: '3'

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: jogjacamp_php
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
        networks:
            - my_network

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: jogjacamp_nginx
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - my_network

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        container_name: jogjacamp_mysql
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        env_file:
            - db.env
        networks:
            - my_network
    ####################################################################################################
    # Adminer
    ####################################################################################################
    adminer:
        container_name: jogjacamp_adminer
        image: adminer
        ports:
            - "8080:8080"
        depends_on:
            - db
        networks:
            - my_network

networks:
  my_network:
    driver: bridge
    